// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUH03zvypUlfaEglfbQ-1f-DDBxatk3dI',
    appId: '1:771002066132:web:03e6c6558df283bf50c741',
    messagingSenderId: '771002066132',
    projectId: 'flutter-firestore-1e0c7',
    authDomain: 'flutter-firestore-1e0c7.firebaseapp.com',
    storageBucket: 'flutter-firestore-1e0c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtWkreOaNKwk6dIlGNGONDiw4IWkNaNso',
    appId: '1:771002066132:android:24afc0d26acf047f50c741',
    messagingSenderId: '771002066132',
    projectId: 'flutter-firestore-1e0c7',
    storageBucket: 'flutter-firestore-1e0c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-WvhhYHOIOM7NJMQ6fSUrvXE6x_Bp99g',
    appId: '1:771002066132:ios:b7efb2c4c4d91dbf50c741',
    messagingSenderId: '771002066132',
    projectId: 'flutter-firestore-1e0c7',
    storageBucket: 'flutter-firestore-1e0c7.firebasestorage.app',
    iosBundleId: 'com.example.tpFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-WvhhYHOIOM7NJMQ6fSUrvXE6x_Bp99g',
    appId: '1:771002066132:ios:b7efb2c4c4d91dbf50c741',
    messagingSenderId: '771002066132',
    projectId: 'flutter-firestore-1e0c7',
    storageBucket: 'flutter-firestore-1e0c7.firebasestorage.app',
    iosBundleId: 'com.example.tpFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUH03zvypUlfaEglfbQ-1f-DDBxatk3dI',
    appId: '1:771002066132:web:248ad8a8d20ecd1350c741',
    messagingSenderId: '771002066132',
    projectId: 'flutter-firestore-1e0c7',
    authDomain: 'flutter-firestore-1e0c7.firebaseapp.com',
    storageBucket: 'flutter-firestore-1e0c7.firebasestorage.app',
  );
}
